name: Manual Version Release

on:
  # Memungkinkan workflow ini dijalankan secara manual dari tab Actions
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Jenis kenaikan versi (sesuai standar npm version)"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease
        default: "prerelease"

jobs:
  release:
    name: Bump Version and Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Synchronize package.json from composer.json
        run: |
          # Pastikan package.json selalu sinkron sebelum menaikkan versi
          COMPOSER_VERSION=$(jq -r .version composer.json)
          npm version --no-git-tag-version --allow-same-version "$COMPOSER_VERSION"

      - name: Bump version using npm
        id: bump_version
        run: |
          BUMP_TYPE="${{ github.event.inputs.version_bump }}"
          NPM_COMMAND="npm version $BUMP_TYPE --no-git-tag-version"

          # PERBAIKAN: Tambahkan --preid=beta jika ini adalah pre-release
          if [[ "$BUMP_TYPE" == "prerelease" || "$BUMP_TYPE" == "prepatch" || "$BUMP_TYPE" == "preminor" || "$BUMP_TYPE" == "premajor" ]]; then
            NPM_COMMAND="$NPM_COMMAND --preid=beta"
          fi

          echo "Running command: $NPM_COMMAND"
          BUMPED_VERSION=$($NPM_COMMAND)
          BUMPED_VERSION=${BUMPED_VERSION#v}
          
          echo "BUMPED_VERSION=$BUMPED_VERSION" >> $GITHUB_OUTPUT
          echo "Version bumped to $BUMPED_VERSION"

      - name: Synchronize composer.json from package.json
        run: |
          # Perbarui versi di composer.json agar sama dengan package.json yang baru
          jq '.version = "${{ steps.bump_version.outputs.BUMPED_VERSION }}"' composer.json > composer.json.tmp && mv composer.json.tmp composer.json

      - name: Commit and push version bump
        run: |
          git add composer.json package.json
          git commit -m "chore: Bump version to ${{ steps.bump_version.outputs.BUMPED_VERSION }}"
          git push

      - name: Create Git Tag & Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.bump_version.outputs.BUMPED_VERSION }}"
          generate_release_notes: true
          # Secara otomatis mendeteksi jika ini adalah pre-release dari nama versi
          prerelease: ${{ contains(steps.bump_version.outputs.BUMPED_VERSION, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
